<?php
$countrys = array(
    "United States" => "us",
    "Netherlands" => "nl",
    "Sweden" => "se",
    "Brazil" => "br",
    "Great Britain" => "gb",
    "Lithuania" => "lt",
    "Ukraine" => "ua",
    "Canada" => "ca",
    "Estonia" => "ee",
    "Chile" => "cl",
    "Finland" => "fi",
    "Japan" => "jp",
    "Australia" => "au",
    "New Zealand" => "nz",
    "Denmark" => "dk",
    "China" => "cn",
    "Philippines" => "ph",
    "Spain" => "es",
    "Czech Republic" => "cz",
    "Germany" => "de",
    "Russian Federation" => "ru",
    "Israel" => "il",
    "Bulgaria" => "bg",
    "Ethiopia" => "et",
    "Norway" => "no",
    "Luxembourg" => "lu",
    "Italy" => "it",
    //Macedonia is displayed weird on steam, so this works.
    "The Former Yugoslav Republic of" => "mk",);
?>
